apiVersion: apps/v1
kind: Deployment  
metadata:
  name: rp-pods
  labels:
    app: yellowapp
    env: dev 
  namespace: devnamepace
  annotations: 
     myecrimage: 808932887013.dkr.ecr.ap-south-1.amazonaws.com/dev/appimageyellow
spec: 
   minReadySeconds: 6
   replicas: 4
   selector: 
      matchExpressions: 
        - key: web
          operator: In 
          values: 
            - yellowapp-pods
        - key: env
          operator: NotIn
          values:
            - dev  
        - key: fortend
          operator: Exists 
   strategy:   
     type: RollingUpdate
     rollingUpdate: 
       maxSurge: 1
       maxUnavailable: 1    
              
   template: 
     metadata:
        name: podlevellabels
        labels:
          web: yellowapp-pods
          env: prod
          fortend: web 
     spec:
       containers:
         - name: yellowimage
           image: longflew/mycssimages:glass
           ports: 
             - name: yellowapp-ports
               containerPort: 80
               protocol: TCP
               resources:
                  # requests:
                  #   cpu: 100m
                  #   memory: 64Mi
                  limits:
                    cpu: 500m
                    memory: 256Mi
           startupProbe:
              initialDelaySeconds: 1
              periodSeconds: 2
              successThreshold: 1
              failureThreshold: 2
              tcpSocket:
                port: 80
           livenessProbe:
              initialDelaySeconds: 2
              periodSeconds: 5
              successThreshold: 1
              failureThreshold: 2
              httpGet:
                path: /
                port: 80
           readinessProbe:
              initialDelaySeconds: 2
              periodSeconds: 5
              successThreshold: 1
              failureThreshold: 2
              timeoutSeconds: 5
              httpGet:
                path: /
                port: 80