apiVersion: apps/v1
kind: Deployment  
metadata:
  name: rp-pods
  labels:
    app: yellowapp
    env: dev 
  namespace: devnamepace
  annotations: 
     myecrimage: 808932887013.dkr.ecr.ap-south-1.amazonaws.com/dev/appimageyellow
spec: 
   minReadySeconds: 6
   replicas: 4
   selector: 
      matchExpressions: 
        - key: web
          operator: In 
          values: 
            - yellowapp-pods
        - key: env
          operator: NotIn
          values:
            - dev  
        - key: fortend
          operator: Exists 
   strategy:   
     type: RollingUpdate
     rollingUpdate: 
       maxSurge: 1
       maxUnavailable: 1    
              
   template: 
     metadata:
        name: podlevellabels
        labels:
          web: yellowapp-pods
          env: prod
          fortend: web 
     spec:
       containers:
         - name: yellowimage
           image: 808932887013.dkr.ecr.ap-south-1.amazonaws.com/dev/appimageyellow:latest
           ports: 
             - name: yellowapp-ports
               containerPort: 80
               protocol: TCP
           startupProbe:
             httpGet: 
               path: "/nikitha"
               port: 80
           livenessProbe:
              tcpSocket:
                port: 80
           readinessProbe:
              exec: 
                command:
                  - echo hi        
           resources:
             requests:
               cpu: 100M
               memory: 200Mi
             limits:
               cpu: 300M
               memory: 300Mi   