apiVersion: apps/v1
kind: ReplicaSet  
metadata:
  name: rp-pods
  labels:
    app: yellowapp
    env: dev 
  namespace: devnamepace
  annotations: 
     myecrimage: 808932887013.dkr.ecr.ap-south-1.amazonaws.com/dev/appimageyellow
spec: 
   minReadySeconds: 6
   replicas: 4
   selector: 
     matchLabels:
        app: yellowapp-pods
   template: 
     metadata:
        name: podlevellabels
        labels:
          app: yellowapp-pods
     spec:
       containers:
         - name: yellowimage
           image: 808932887013.dkr.ecr.ap-south-1.amazonaws.com/dev/appimageyellow:latest
           ports: 
             - name: yellowapp-ports
               containerPort: 80
               protocol: TCP
           startupProbe:
             httpGet: 
               path: "/nikitha"
               port: 80
           livenessProbe:
              tcpSocket:
                port: 80
           readinessProbe:
              exec: 
                command:
                  - echo hi 
                  - touch laxmikanthfile         
           resources:
             requests:
               cpu: 100M
               memory: 150Mi
             limits:
               cpu: 200M
               memory: 250Mi   